In [3]:
a=[1,2,3,3]

#비추천 len(a) 에서 숫자 세기 + range 에서 list 생성
for i in range(len(a)):
    print(i)

#추천 list를 객체화
for i in a:
    print(i)




0
1
2
3
1
2
3
3


In [31]:
import random

#복원추출, 비복원추출

for i in range(6):
    num = random.randrange(1,46) # 복원추출
    print(num,end='/')


26/31/28/31/2/4/

In [11]:
import random

name = '가,나,다,라,마,바'
nameList = name.split(',')
print(nameList)
dayList='월,화,수,목,금'.split(',')
#nameLen = len(nameList)


#emuerate 는 자동으로 0,1,2,3 ... 숫자값을 가지게 됨
for cnt,i in enumerate(dayList):
    namePrn=random.choice(nameList)
    print(cnt+1 ,'번', i,'==>',namePrn)

['가', '나', '다', '라', '마', '바']
1 번 월 ==> 마
2 번 화 ==> 마
3 번 수 ==> 가
4 번 목 ==> 라
5 번 금 ==> 나


In [12]:
name = '가,나,다,라,마,바'
nameList = name.split(',')
print(nameList)

dayList = '월,화,수,목,금'.split(',')

# Check if the number of names is greater than or equal to the number of days
if len(nameList) >= len(dayList):
    sampled_names = random.sample(nameList, len(dayList))

    for day, sampled_name in zip(dayList, sampled_names):
        print(day, '==>', sampled_name)
else:
    print("Error: Not enough names for each day.")

['가', '나', '다', '라', '마', '바']
월 ==> 다
화 ==> 마
수 ==> 바
목 ==> 나
금 ==> 라


In [11]:
import numpy as np

# Create an initial NumPy array
arr = np.array([[1, 2, 3],[5,6,7]])

print(arr)

# Append a scalar element
print(np.append(arr[0], 4))


list_a = [[1,2,3],[5,6,7]]

print(arr)


[[1 2 3]
 [5 6 7]]
[1 2 3 4]
[[1 2 3]
 [5 6 7]]


In [12]:
arr.shape


list_a.shape

AttributeError: 'list' object has no attribute 'shape'